#!/usr/bin/env python3
"""Generate two static catalogues and a stable JSON index, without network access."""
from __future__ import annotations

import argparse
import html
import json
from pathlib import Path

from case_studies import INDEX, ROOT, canonical_records, label, load_records, schema, validate_records

REPO = "https://github.com/damjan-popic/digital-humanities-handbook/blob/main/"


def plain(value: str) -> str:
    """Render authored prose as text rather than active card markup."""
    return html.escape(value, quote=False).replace("*", "&#42;").replace("[", "&#91;").replace("]", "&#93;").replace("`", "&#96;").replace("\n", " ")


def catalogue(records: list[dict], locale: str, definitions: dict) -> str:
    sl = locale == "sl"
    title = "Študije primerov" if sl else "Case studies"
    intro = (
        "Kako raziskovalno vprašanje, viri in odločitve pri modeliranju omejujejo trditve digitalnega projekta? "
        "Katalog ločuje opis projekta, pregledano gradivo in lokalni preizkus. Javno dostopna koda še ne pomeni dovoljenja za ponovno uporabo."
        if sl else
        "How do a research question, sources and modelling decisions limit a digital project's claims? "
        "This catalogue distinguishes project description, inspected evidence and local testing. Public source code does not itself grant reuse permission."
    )
    lines = ["---", f'title: "{title}"', "---", "", "<!-- Generated by scripts/build_case_study_index.py; edit data/case-studies.yml. -->", "",
             f"# {title}", "", intro, ""]
    if sl:
        lines += ["Kataloški opisi so strojno podprt osnutek; potreben je človeški jezikovni pregled. "
                  "Angleške nadomestne strani so označene na vsaki kartici in se ne štejejo za slovenske prevode študij.", ""]
    lines += [f"[{('Predloga kritične študije primera' if sl else 'Critical case-study template')}](../contribute/project-template.md) · "
              f"[{('Datirani pregled vseh primerov (angleško)' if sl else 'Dated audit of every case')}]({REPO}release/case-study-audit.md) · "
              f"[{('Pomen metapodatkovnih oznak (angleško)' if sl else 'Metadata vocabulary and limits')}]({REPO}data/case-study-metadata.md)", ""]
    en_count = sum(record["page_en"] is not None for record in records)
    sl_count = sum(record["page_sl"] is not None for record in records)
    fallback = sum(record["translation_status"] == "english-fallback" for record in records)
    lines += [(f"**{len(records)} primerov; {en_count} angleških strani; {sl_count} slovenskih strani; {fallback} angleških nadomestnih strani.**"
               if sl else f"**{len(records)} cases; {en_count} English pages; {sl_count} Slovene pages; {fallback} English fallbacks.**"), "",
              "## Katalog" if sl else "## Catalogue", "", '<div class="grid cards" markdown>', ""]
    facets = (
        ("method_domains", "Method/domain", "Metoda/področje"),
        ("source_types", "Source type", "Vrsta vira"),
        ("inspection_modes", "Inspection modes", "Načini pregleda"),
        ("languages_regions", "Language/region", "Jezik/prostor"),
        ("code_availability", "Code availability", "Dostopnost kode"),
        ("reusable_data_availability", "Reusable data", "Podatki za ponovno uporabo"),
        ("rights_status", "Rights summary", "Povzetek pravic"),
        ("lifecycle_status", "Project lifecycle", "Življenjski cikel projekta"),
        ("editorial_disposition", "Handbook editorial disposition", "Uredniška odločitev za priročnik"),
        ("translation_status", "Translation", "Prevod"),
    )
    for record in records:
        language = locale if record[f"page_{locale}"] else ("en" if record["page_en"] else "sl")
        title = record[f"title_{language}"] or record["case_id"]
        summary = record[f"short_summary_{language}"] or ""
        target = record[f"page_{language}"]
        href = Path(target).name if target else REPO + record["audit_record"]
        if target and not sl and language == "sl":
            href = f"https://damjan-popic.github.io/digital-humanities-handbook/sl/case-studies/{record['slug']}/"
        suffix = " — angleška nadomestna stran" if target and sl and language == "en" else (
            " — Slovene-only page" if target and not sl and language == "sl" else "")
        lines += [f"-   **[{plain(title)}]({href}){suffix}**", "",
                  f"    {plain(summary)}", "",
                  f"    **{label('content_standard', record['content_standard'], locale, definitions)}**", ""]
        for field, en_label, sl_label in facets:
            values = record[field] if isinstance(record[field], list) else [record[field]]
            display = "; ".join(label(field, value, locale, definitions) for value in values)
            lines.append(f"    - {sl_label if sl else en_label}: {display}")
        lines += [f"    - {('Dokazna podlaga' if sl else 'Evidence')}: {label('evidence_status', record['evidence_status'], locale, definitions)}",
                  f"    - {('Povezava repozitorija z uredništvom' if sl else 'Repository relationship')}: {label('repository_relationship', record['repository_relationship'], locale, definitions)}",
                  f"    - {('Preverjeno' if sl else 'Checked')}: {record['last_checked']}; [{('zapis pregleda (angleško)' if sl else 'audit record')}]({REPO}{record['audit_record']})", "",
                  f"    **{('Pravice po sestavinah' if sl else 'Component rights')}**", ""]
        for component in record["rights_components"]:
            name = label("rights_component", component["component"], locale, definitions)
            status = label("rights_component_status", component["status"], locale, definitions)
            terms = component["licence_or_terms"]
            details = (f"; {('oznaka licence ali zapis pogojev (neprevedeno)' if sl else 'licence identifier or recorded terms')}: {plain(terms)}"
                       if terms is not None else "")
            lines.append(f"    - {name}: {status}{details}; "
                         f"[{('obseg in dokazila (angleško)' if sl else 'scope and evidence')}]({REPO}{component['audit_locator']})")
        lines.append("")
    lines += ["</div>", "", "## Kako berete oznake" if sl else "## Reading the labels", "",
              ("Podedovani primeri so pregledani, vendar še ne izpolnjujejo standarda v1. Datirani pregled navaja vrzeli in nadaljnje delo; "
               "dosegljivost spletne strani sama po sebi ne dokazuje vzdrževanja, licenca kode pa ne določa pravic za vse vhodne podatke. "
               "Življenjski cikel opisuje stanje projekta, uredniška odločitev pa nadaljnjo obravnavo v priročniku: "
               "predlog za arhiviranje primera ne pomeni, da je projekt arhiviran. Deklarirana licenca je ohranjena, "
               "četudi njen celotni obseg še ni preverjen; sama deklaracija ne spremeni povzetka pravic v preverjeno dovoljenje. "
               "Arhivirani in nedostopni projekti ter uredniško odloženi primeri ostajajo vidni, niso pa priporočilo za nepreverjen zagon."
               if sl else "Audited legacy cases are not v1-complete. The dated audit records gaps and follow-up work; "
               "a reachable website does not prove maintenance, and a code licence does not settle rights in all inputs. "
               "Project lifecycle describes the project's observed state; handbook editorial disposition describes its treatment here: "
               "a recommendation to archive a case does not mean that the project is archived. A declared licence is preserved even "
               "when its full scope remains unverified; declaration alone does not turn the rights summary into verified permission. "
               "Archived or unavailable projects and editorially deferred cases remain visible, not recommendations to run unchecked software."), ""]
    return "\n".join(lines)


def generated(records: list[dict], root: Path = ROOT) -> dict[str, str]:
    records = canonical_records(records, root)
    definitions = schema(root)["$defs"]
    return {INDEX: json.dumps(records, ensure_ascii=False, indent=2) + "\n",
            **{f"docs/{locale}/case-studies/index.md": catalogue(records, locale, definitions)
               for locale in ("en", "sl")}}


def check_generated(records: list[dict], root: Path = ROOT) -> None:
    for relative, expected in generated(records, root).items():
        path = root / relative
        if not path.is_file() or path.read_bytes() != expected.encode("utf-8"):
            raise ValueError(f"Metadata/catalogue drift: {relative}; run python scripts/build_case_study_index.py")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check bytes without rewriting files")
    args = parser.parse_args()
    records = load_records()
    validate_records(records)
    if args.check:
        check_generated(records)
    else:
        for relative, text in generated(records).items():
            (ROOT / relative).write_text(text, encoding="utf-8", newline="\n")
            print(f"Wrote {relative}")
    print(f"Case catalogue: {len(records)} records in case_id order; 2 static language indexes; "
          f"{sum(record['page_sl'] is not None for record in records)} Slovene case pages; "
          f"{sum(record['translation_status'] == 'english-fallback' for record in records)} explicitly labelled English fallbacks.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
